### ISSUE TITLE
rows:procについて

### ISSUE THREAD

**Issue by ghost** [joker1007/embulk-filter-ruby_proc#4]
embulk-filter-ruby_procを使用してデータの処理をさせて頂いています。

```yaml
filters:
  requires:
  - cgi
  rows:
  - proc: |
        ->(record) do
         [record.dup, record.dup.tap {|r| r["comment"] = r["comment"].gsub('\n', ' ')}]
        end
  type: ruby_proc
```
のような設定ファイルを作成したのですが以下のようなエラーが返ってきました。
`Error: java.lang.IllegalArgumentException: Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: N/A; line: -1, column: -1]
`
これは何に原因でしょうか
